# Generated by Django 6.0.6 on 2026-06-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CONTENT_SUPERVISOR', 'Content Supervisor'), ('TECH_SUPERVISOR', 'Tech Supervisor'), ('CONTENT_INTERN', 'Content Intern'), ('TECH_INTERN', 'Tech Intern')], default='ADMIN', max_length=32),
        ),
    ]
