# Generated by Django 6.0.6 on 2026-06-10 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_metadata_tokens_profile_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_id', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=60, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_link', models.TextField(blank=True, help_text='Link to full task details (any URL)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('rejection_remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='attendancelog',
            name='dashboard_a_login_d_9e88b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='dashboard_s_task_ty_d4be97_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='dashboard_s_intern__5a5ab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='dashboard_t_departm_890a49_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='dashboard_t_raised__3433ce_idx',
        ),
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note to supervisor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='intern_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='supervisor_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='dashboard.announcement'),
        ),
        migrations.AddField(
            model_name='announcementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='dashboard.assignedtask'),
        ),
        migrations.AddField(
            model_name='submissionread',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='dashboard.submission'),
        ),
        migrations.AddField(
            model_name='submissionread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskread',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='dashboard.assignedtask'),
        ),
        migrations.AddField(
            model_name='taskread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='subject_code_or_task_title',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task_type',
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('user', 'announcement'), name='unique_ann_read'),
        ),
        migrations.AddConstraint(
            model_name='submissionread',
            constraint=models.UniqueConstraint(fields=('user', 'submission'), name='unique_submission_read'),
        ),
        migrations.AddConstraint(
            model_name='taskread',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_task_read'),
        ),
    ]
