# Generated by Django 6.0.6 on 2026-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_internaccountread'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='supervisor_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
