# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_ticket_supervisor_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
